# general settings
name: train_HAT_Dacon_base
model_type: HATModel
scale: 4
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: train
    type: PairedImageDataset
    dataroot_gt: ../train_val_split_seed0_size0.1/split64/train/hr
    dataroot_lq: ../train_val_split_seed0_size0.1/split64/train/lr
    meta_info_file: ./hat/data/meta_info/meta_info_train_hr.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true  # horizontalflip
    use_rot: false  # verticalflip + rotation

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: true

  val_1:
    name: valid
    type: PairedImageDataset
    dataroot_gt: ../train_val_split_seed0_size0.1/split64/valid/hr
    dataroot_lq: ../train_val_split_seed0_size0.1/split64/valid/lr
    io_backend:
      type: disk

# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ./experiments/pretrained_models/HAT_SRx4_ImageNet-pretrain.pth
  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

    # type: SGD
    # lr: !!float 1e-4
    # weight_decay: 0

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [47232]
    restart_weights: [1.0]
    eta_min: !!float 1e-6

    # type: MultiStepLR
    # milestones: [23616, 35424, 41328, 44280]
    # gamma: 0.5


  total_iter: 47232  # 1 epoch : 47232
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
    # type: PSNRLoss  # it will return minus value
    # loss_weight: 1.0
    # reduction: mean
    # toY: true  # on y channel

# validation settings
val:
  val_freq: 50000
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0  # exlude border
      test_y_channel: true  # on y channel
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 0  # exlude border
      test_y_channel: true  # on y channel
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 2952  # 2952
  save_checkpoint_freq: 11808
  use_tb_logger: true
  wandb:
    project: Dacon_SR
    resume_id: ~
